# Generated by Django 6.0.3 on 2026-03-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-availability', 'title']},
        ),
    ]
